canFlyWhenDead: false
endTime: 10
prepareTime: 10
lobbyTime: 10
maxGameLength: 6000
minPlayers: 2
maxPlayers: 8
description: 'Try to get rid of the Potato by smacking a player! Last one alive wins!'
potatoTime: 20
commandsOnWin:
  - 'Example Command'