name: HotPotato
version: 1.2.1
main: me.avery246813579.hotpotato.HotPotato
commands: 
  hp:
    description: Updates a spawn.
  hotpotato:
    description: Creates a arena.
permissions:
  hotpotato.signs:
    description: Allows players to create signs.
    default: op
  hotpotato.command.create:
    description: Allows players to create a arena.
    default: op
  hotpotato.commands.join:
    description: Allows players to join a arena.
    default: true
  hotpotato.commands.leave:
    description: Allows players to leave a arena.
    default: true
  hotpotato.commands.start:
    description: Allows players to start a arena.
    default: op
  hotpotato.commands.stop:
    description: Allows players to stop a arena.
    default: op
  hotpotato.commands.update:
    description: Allows players to update a arena.
    default: op   